language: go

go: 
    - 1.7.x

script: 
    - go get github.com/gorilla/mux 
    - go test ./server/apiv0
    - go test ./client/
    - go build -o net_server ./server
    - go build -o net_client ./client
    - sh ./system-test.sh
